//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7_Elephant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int C_product_id { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string url { get; set; }
    }
}
